CREATE TABLE users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
);

CREATE TABLE carts
(
  CartID INT
  AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL UNIQUE,
    Items JSON,
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
  UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY
  (UserID) REFERENCES users
  (UserID) ON
  DELETE CASCADE
);

CREATE TABLE carts (
    CartID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL UNIQUE,
    Items JSON,
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);

CREATE TABLE products
(
  ProductID INT
  AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR
  (100) NOT NULL,
    Price DECIMAL
  (10, 2) NOT NULL,
    Stock INT DEFAULT 0,
    Description TEXT
);